DOMAIN = "yi-hack"

DEFAULT_BRAND = "yi-hack"

MSTAR = "yi-hack-mstar"
ALLWINNER = "yi-hack-allwinner"
ALLWINNERV2 = "yi-hack-allwinner-v2"

DEFAULT_HOST = ""
DEFAULT_PORT = 8080
DEFAULT_USERNAME = ""
DEFAULT_PASSWORD = ""
DEFAULT_EXTRA_ARGUMENTS = "-rtsp_transport tcp"

SERVICE_PTZ = "ptz"

CONF_HACK_NAME = "HACK_NAME"
CONF_SERIAL = "SERIAL_NUMBER"
CONF_PTZ = "PTZ"
CONF_RTSP_PORT = "RTSP_PORT"
CONF_MAC_ADDRESS = "MAC_ADDRESS"
CONF_MQTT_PREFIX = "MQTT_PREFIX"
CONF_TOPIC_STATUS = "TOPIC_BIRTH_WILL"
CONF_TOPIC_MOTION_DETECTION = "TOPIC_MOTION"
CONF_TOPIC_AI_HUMAN_DETECTION = "TOPIC_AI_HUMAN_DETECTION"
CONF_TOPIC_SOUND_DETECTION = "TOPIC_SOUND_DETECTION"
CONF_TOPIC_BABY_CRYING = "TOPIC_BABY_CRYING"
CONF_TOPIC_MOTION_DETECTION_IMAGE = "TOPIC_MOTION_IMAGE"
CONF_DONE = "CONF_DONE"
