DOMAIN = "yi-hack"

DEFAULT_BRAND = "yi-hack"

DEFAULT_HOST = ""
DEFAULT_PORT = 8080
DEFAULT_USERNAME = ""
DEFAULT_PASSWORD = ""
DEFAULT_EXTRA_ARGUMENTS = "-rtsp_transport tcp"

CONF_SERIAL = "SERIAL_NUMBER"
CONF_RTSP_PORT = "RTSP_PORT"
CONF_MAC_ADDRESS = "MAC_ADDRESS"
CONF_MQTT_PREFIX = "MQTT_PREFIX"
CONF_TOPIC_STATUS = "TOPIC_BIRTH_WILL"
CONF_TOPIC_MOTION_DETECTION = "TOPIC_MOTION"
CONF_TOPIC_BABY_CRYING = "TOPIC_BABY_CRYING"
CONF_TOPIC_MOTION_DETECTION_IMAGE = "TOPIC_MOTION_IMAGE"
